In [17]:
import numpy as np
import pandas as pd
# {'Yes': ["Mango": 10], 'No': [{"Apple": 5}], ["Coconut": 15}]}
df = pd.DataFrame({"Mango": 10, "Apple": 5, "Coconut": 15})
df

ValueError: If using all scalar values, you must pass an index

In [15]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)
x[0] = 10
print(x)
print(y)

None
[1 2 3 4 5]
[10  2  3  4  5]
[1 2 3 4 5]
